
SCENARIO_RUN_START   <- Sys.time()

# Do this first bit if the model was called from the command line
if (exists("SYSTEM_COMMAND_ARGS")) {
  
  if (length(SYSTEM_COMMAND_ARGS) >= 1) SCENARIO_NAME <- SYSTEM_COMMAND_ARGS[1] else SCENARIO_NAME <- "base"
  if (length(SYSTEM_COMMAND_ARGS) >= 2) SCENARIO_YEAR <- SYSTEM_COMMAND_ARGS[2] else SCENARIO_YEAR <- 2015
  if (length(SYSTEM_COMMAND_ARGS) >= 3) SCENARIO_RUN_FIRMSYN <- as.logical(SYSTEM_COMMAND_ARGS[3]) else SCENARIO_RUN_FIRMSYN <- TRUE
  if (length(SYSTEM_COMMAND_ARGS) >= 4) SCENARIO_RUN_SCM     <- as.logical(SYSTEM_COMMAND_ARGS[4]) else SCENARIO_RUN_SCM <- TRUE
  if (length(SYSTEM_COMMAND_ARGS) >= 5) SCENARIO_RUN_FTTM    <- as.logical(SYSTEM_COMMAND_ARGS[5]) else SCENARIO_RUN_FTTM <- TRUE
  if (length(SYSTEM_COMMAND_ARGS) >= 6) SCENARIO_RUN_CVTM    <- as.logical(SYSTEM_COMMAND_ARGS[6]) else SCENARIO_RUN_CVTM <- TRUE
  if (length(SYSTEM_COMMAND_ARGS) >= 7) SCENARIO_RUN_TT      <- as.logical(SYSTEM_COMMAND_ARGS[7]) else SCENARIO_RUN_TT <- TRUE
  
} else {
  
  SCENARIO_NAME <- "base"
  SCENARIO_YEAR <- 2015
  SCENARIO_RUN_FIRMSYN <- TRUE
  SCENARIO_RUN_SCM <- TRUE
  SCENARIO_RUN_FTTM <- TRUE
  SCENARIO_RUN_CVTM <- TRUE
  SCENARIO_RUN_TT <- TRUE
  
}

SCENARIO_INPUT_PATH  <- file.path(SYSTEM_APP_PATH, "scenarios", SCENARIO_NAME, "inputs")
SCENARIO_OUTPUT_PATH <- file.path(SYSTEM_APP_PATH, "scenarios", SCENARIO_NAME, "outputs")
SCENARIO_LOG_PATH    <- file.path(SCENARIO_OUTPUT_PATH, "log")
